# Generated by Django 5.2.4 on 2025-08-23 17:26

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contact', models.CharField(max_length=15)),
                ('Role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='teachers/')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_edunexus.department')),
                ('teacher', models.OneToOneField(limit_choices_to={'Role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, to='app_edunexus.user')),
            ],
            options={
                'db_table': 'Teacher_Profile',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='students/')),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_edunexus.department')),
                ('student', models.OneToOneField(limit_choices_to={'Role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to='app_edunexus.user')),
            ],
            options={
                'db_table': 'Student_Profile',
            },
        ),
    ]
