# Generated by Django 5.2.4 on 2025-09-01 05:16

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_edunexus', '0002_ebook_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='ebooks/'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_edunexus.user')),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
    ]
