# Generated by Django 5.2.4 on 2025-09-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_edunexus', '0003_alter_ebook_file_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_by',
        ),
    ]
